name: CMake

on:
push:
tags:
- v**

jobs:
build_packages_Linux:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Configure Solver
run: cmake ${{github.workspace}} -B ${{github.workspace}}/build
- name: Build Solver
run: cmake —build ${{github.workspace}}/build
- name: Build package
run: cmake —build ${{github.workspace}}/build —target package
- name: Build source package
run: cmake —build ${{github.workspace}}/build —target package_source
- name: Upload artifacts
uses: actions/upload-artifact@v2
with:
name: my-artifacts
path: |
build/*.deb
build/*.tar.gz
build/*.zip
working-directory: ${{github.workspace}}
- name: Create Release
uses: actions/create-release@v1
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
with:
tag_name: ${{ github.ref }}
release_name: Release ${{ github.ref_name }}
body: Release ${{ github.ref_name }}
draft: false
prerelease: false
- name: Attach Artifacts to Release
uses: actions/upload-release-asset@v1
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
with:
upload_url: ${{ steps.create_release.outputs.upload_url }}
asset_path: build/
asset_name: my-artifacts
asset_content_type: application/zip
