name: CMake

on:
 push:
   tags:
     - v**

jobs: 

  build_packages_Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure Solver
      run: cmake ${{github.workspace}} -B ${{github.workspace}}/build -D PRINT_VERSION=${GITHUB_REF_NAME#v}

    - name: Build Solver
      run: cmake --build ${{github.workspace}}/build

    - name: Build package
      run: cmake --build ${{github.workspace}}/build --target package

    - name: Build source package
      run: cmake --build ${{github.workspace}}/build --target package_source

   - name: Upload TGZ
      id  : TGZ
      uses: actions/upload-release-asset@v1
      env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
       upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
       asset_path: ./cmake/solver-0.1.1-Linux.tar.gz
       asset_name: Solver-${{ github.ref_name }}.tar.gz
       asset_content_type: code/tgz
       
    - name: Upload ZIP
      id  : ZIP
      uses: actions/upload-release-asset@v1
      env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
       upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
       asset_path: ./cmake/solver-0.1.1-Linux.zip
       asset_name: Solver-${{ github.ref_name }}.zip
       asset_content_type: code/zip
